// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGhiDKq0tON-N87s6Sk0nMzwNcoHG5mFU',
    appId: '1:666337261439:web:7b2c9200536405b0f78c4a',
    messagingSenderId: '666337261439',
    projectId: 'hip-well-400702',
    authDomain: 'hip-well-400702.firebaseapp.com',
    storageBucket: 'hip-well-400702.appspot.com',
    measurementId: 'G-SY0K4N4PPV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXHcfX2E1Kj3wHTWYQklS0GAZcWBlFwvY',
    appId: '1:666337261439:android:a7428d1585328ad3f78c4a',
    messagingSenderId: '666337261439',
    projectId: 'hip-well-400702',
    storageBucket: 'hip-well-400702.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcJH7b0svTb2hFehJdmpTVP99atamuooc',
    appId: '1:666337261439:ios:000c8a3c155bdd5bf78c4a',
    messagingSenderId: '666337261439',
    projectId: 'hip-well-400702',
    storageBucket: 'hip-well-400702.appspot.com',
    iosBundleId: 'com.example.delivery',
  );
}
